title: Mustafa Fakhar
description: This portfolio showcases my skills and abilities as a data analyst.
#show_downloads: true
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
