title: Mustafa Fakhar
description: This portfolio showcases my skills and abilities as a data analyst.
Links: ![LinkedIn](https://img.shields.io/badge/LinkedIn-Connect-blue?style=flat&logo=linkedin)https://www.linkedin.com/in/mustafa-fakhar-1856661b0/
#show_downloads: true
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
